CC = c++ 

FLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp vector2.cpp

NAME = cartesianGraph

all : $(NAME)

$(NAME) : $(SRCS)
	$(CC) $(FLAGS) $(SRCS) -o $(NAME)

clean :
	rm -rf $(NAME)

fclean : clean

re : fclean allCC = c++

